# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtemplate',
            name='template_path',
            field=models.TextField(default=b''),
        ),
    ]
